scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/sro_v1alpha1_specialresource_cr.yaml"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crds/sro_v1alpha1_specialresource_cr.yaml"
        csv-path: "deploy/olm-catalog/special-resource-operator/4.2.0/special-resource-operator.v4.2.0.clusterserviceversion.yaml"
    # Configuring external plugin with no args